# -*- coding: utf-8 -*-
"""NovaPay_Fraud_Detection_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r30snuNZT4M5JLuEY4vLofUgY0bPT82Y

###NOVA PAY FRAUD DETECTION SYSTEM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

uploaded = files.upload()
df = pd.read_csv('nova_pay_combined.csv')  # Load dataset
df

print (df.shape)

df.isnull().sum()  # Check for missing values

df.info()   # Check datatype

"""#### HANDLE INCONSISTENT DATATYPE"""

# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')  # This function already handles missing values in the timestamp

# Convert amount_src to float safely
df['amount_src'] = pd.to_numeric(df['amount_src'], errors='coerce')

# Check both conversions
print(df[['timestamp', 'amount_src']].dtypes)

"""####HANDLE MISSING VALUES

#### For 'amount_usd'
The process involved:
* Estimate the missing amount_usd using the relationship between amount_src and amount_usd.

* Then calculate average exchange rates per source_currency using transactions where amount_usd is already available (amount_usd / amount_src).

* Store these rates in a lookup dictionary for efficient reference during imputation.
"""

df["source_currency"].value_counts()   # Check source currency counts

# Select rows where amount_usd is present
df_with_usd = df[df['amount_usd'].notna()]

# Compute average exchange rate per source currency
# (mean of amount_usd / amount_src)
exchange_rate_lookup = df_with_usd.groupby('source_currency').apply(
    lambda x: (x['amount_usd'] / x['amount_src']).mean()
).to_dict()

print("Currency conversion lookup:", exchange_rate_lookup)

"""#####To fill missing values
* Impute missing amount_usd by multiplying amount_src with the corresponding currency exchange rate.

* Use a default rate of 1 if a currency is not found in the lookup.

* Preserve existing amount_usd values to maintain data integrity.
"""

# Fill missing amount_usd using the lookup, defaulting to 1 if currency not found
def fill_amount_usd(row):
    if pd.notna(row['amount_usd']):
        return row['amount_usd']
    else:
        rate = exchange_rate_lookup.get(row['source_currency'], 1)
        return row['amount_src'] * rate

df['amount_usd'] = df.apply(fill_amount_usd, axis=1)

# Check if missing values remain
print(df['amount_usd'].isna().sum())

"""#### For 'fee'
Missing values were handled by:
* First checking column availability to ensure the fee column exists before applying the operation.

* Then group transactions by channel to capture channel-specific fee patterns (e.g., web, mobile, ATM).

* Proceed to fill missing fee values within each channel using the median fee of that channel, preserving typical fee structures across transaction types.

* And finally, handle remaining missing values by filling them with the overall median fee of the dataset.
"""

if 'fee' in df.columns:
  if 'channel' in df.columns:
      df['fee'] = df.groupby('channel')['fee'].transform(lambda s: s.fillna(s.median()))

  df['fee'] = df['fee'].fillna(df['fee'].median())

# Check remaining missing values
missing_fee = df['fee'].isna().sum()
print(f"Remaining missing fee values: {missing_fee}")

"""#### For 'ip_country'
Fill missing values by:
* Confirming column availability by checking both ip_country and home_country exist before applying the operation.

* Using home_country as a fallback to fill missing ip_country values when the IP-based country is unavailable.

* Leveraging customer geographic information to maintain realistic location data for transactions thereby maintaining data integrity.
"""

if {'ip_country', 'home_country'}.issubset(df.columns):
  df['ip_country'] = df['ip_country'].fillna(df['home_country'])

# Check remaining missing values
missing_ip_country = df['ip_country'].isna().sum()
print(f"Remaining missing ip_country values: {missing_ip_country}")

"""#### For 'kyc_tier'

To handle missing values in 'kyc_tier';

* First confirm column availability before applying the operation.

* Next, perform mode imputation to determine the most frequent value of kyc_tier to represent the most common verification level among customers.

* Then use the mode as the replacement value to fill missing kyc_tier entries, preserving the typical distribution of verification levels in the dataset.

* Finally, apply a fallback value ('standard') if the mode cannot be determined - this ensures the process does not fail.
"""

if 'kyc_tier' in df.columns:
  mode_kyc = df['kyc_tier'].mode().iloc[0] if not df['kyc_tier'].mode().empty else 'standard'
  df['kyc_tier'] = df['kyc_tier'].fillna(mode_kyc)


# Check remaining missing values
missing_kyc_tier = df['kyc_tier'].isna().sum()
print(f"Remaining missing kyc_tier values: {missing_kyc_tier}")

"""#### For 'device_trust_score'
Missing values in this column were handled by:

* First confirm column availability to ensure device_trust_score exists before applying imputation.

* Then group transactions by new_device and kyc_tier to capture trust score patterns related to device novelty and customer verification level.

* Next, Fill missing device_trust_score values within each group using the median trust score of that group - this preserves realistic behavioural patterns across device and customer segments.

* Finally, handle any remaining missing values by filling them with the overall median device_trust_score for the dataset and validate.
"""

if 'device_trust_score' in df.columns:
  if {'new_device', 'kyc_tier'}.issubset(df.columns):
    df['device_trust_score'] = df.groupby(['new_device', 'kyc_tier'])['device_trust_score'] \
                                      .transform(lambda s: s.fillna (s.median()))
  df['device_trust_score'] = df ['device_trust_score'].fillna(df['device_trust_score'].median())

# Check remaining missing values
missing_device_trust_score = df['device_trust_score'].isna().sum()
print(f"Remaining missing device_trust_score values: {missing_device_trust_score}")

df.isnull().sum()

df.dropna(inplace = True)

# Dropped remaining missing values in 'timestamp' and 'amount_src' as these are minimal
# and 'timestamp' has already been standardized to datetime so no need for further handling.
# Missing values in 'ip_address' are also dropped since it is an identifier with limited predictive value.

# CHECK AGAIN
df.isnull().sum()

# CONFIRM APPROPRIATE DATATYPE FOR RESPECTIVE FEATURES
df.info()

df.describe(include = 'all')

"""From the above outputs, it can be observed that further checks is required to ensure data consistency and integrity before downstream analyses.

#### DATA CLEANING AND PREPARATION 2: SANITY CHECK
"""

# Define key numeric columns where negative values are not expected
numeric_cols = [
    'amount_src', 'amount_usd', 'fee', 'exchange_rate_src_to_dest',
    'ip_risk_score', 'device_trust_score', 'risk_score_internal',
    'txn_velocity_1h', 'txn_velocity_24h', 'corridor_risk', 'account_age_days',
    'chargeback_history_count'
]

# Count negative values per column
neg_counts = (df[numeric_cols] < 0).sum()
print("Negative value counts per column:\n", neg_counts)

# Sum total negative counts across all these columns
total_negatives = neg_counts.sum()
print(f"\nTotal negative values across all key numeric columns: {total_negatives}")

# Columns with negative values
neg_cols = ['amount_src', 'fee', 'device_trust_score', 'txn_velocity_1h']

# Replace negative values with 0
for col in neg_cols:
    df[col] = df[col].apply(lambda x: x if x >= 0 else 0)

# Verify that negatives are gone
neg_counts_after = (df[neg_cols] < 0).sum()
print("Negative value counts after handling:\n", neg_counts_after)

(df['amount_usd']/ df['amount_src']).describe()

"""####OBSERVATIONS
After filling missing values and addressing negative entries, some transactions still show implausible exchange rates (amount_usd ÷ amount_src) with a max value of 62.16 and an average of 1.03 - this could be due to data entry errors or extreme values.
These outliers can distort model learning and predictions.
"""

# Compute implied exchange rate
df['implied_rate'] = df['amount_usd'] / df['amount_src']

# Calculate interquartile range (IQR) for implied rates
Q1 = df['implied_rate'].quantile(0.25)
Q3 = df['implied_rate'].quantile(0.75)
IQR = Q3 - Q1

# Define lower and upper bounds (Using 1.5*IQR which is standard for outliers)
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Step 1: Identify outliers
rate_outliers = df[(df['implied_rate'] < lower_bound) | (df['implied_rate'] > upper_bound)]
print(f"Number of outlier rows: {rate_outliers.shape[0]}")

(rate_outliers[['transaction_id', 'source_currency', 'dest_currency', 'amount_src', 'amount_usd', 'implied_rate']])

"""So, by capping or recalculating amount_usd using the average exchange rate per source currency, we can ensure that all values remain realistic, maintain data integrity, and reduce the risk of model bias caused by erroneous extreme values."""

# Step 2: Compute median exchange rate per source_currency
median_rate_lookup = df.groupby('source_currency')['implied_rate'].median().to_dict()

# Step 3: Replace outliers with median rate per source currency
def correct_implied_rate(row):
    rate = row['implied_rate']
    source = row['source_currency']
    median_rate = median_rate_lookup.get(source, 1)  # fallback to 1 if not found
    # If the rate is an outlier, replace with median
    if rate < lower_bound or rate > upper_bound:
        return median_rate
    else:
        return rate

df['implied_rate'] = df.apply(correct_implied_rate, axis=1)

# Step 4: Update amount_usd to reflect corrected implied rate
df['amount_usd'] = df['amount_src'] * df['implied_rate']

# Step 5: Sanity check
(df[['transaction_id', 'source_currency', 'dest_currency', 'amount_src', 'amount_usd', 'implied_rate']].head())

(df['amount_usd']/ df['amount_src']).describe()  #  No more extreme values observed from output

# Extra Step 6: Verify all implied rates are within bounds
lower_bound = 0.5
upper_bound = 5.0

# Identify any remaining outliers
remaining_outliers = df[(df['implied_rate'] < lower_bound) | (df['implied_rate'] > upper_bound)]

print(f"Number of remaining outlier rows: {remaining_outliers.shape[0]}")
if remaining_outliers.shape[0] == 0:
    print("Sanity Checked:")
    print("All implied rates are now within the acceptable range.")
else:
    print("Some implied rates are still outside the expected range:")
    print(remaining_outliers[['transaction_id', 'source_currency', 'dest_currency', 'amount_src', 'amount_usd', 'implied_rate']])

# TASK: Remove duplicates and invalid or future-dated transactions.

df[df['timestamp'] > pd.Timestamp.utcnow()]

# Checks for futuristic leakage. In this case, 0
# this ensures that no future data is influencing predictive outcome

df['location_mismatch'].value_counts()    # REASONABLE DISTRIBUTION; NO NEED FOR FURTHER ANALYSIS

# Check unique values in selected categorical columns
print("Unique channels:", df['channel'].unique())
print("Unique source currencies:", df['source_currency'].unique())
print("Unique destination currencies:", df['dest_currency'].unique())
print("Unique KYC tiers:", df['kyc_tier'].unique())

"""The above analysis confirms that there are inconsistencies and typos in the categorical columns that need standardization before modeling.

Below analyses handles these inconsistencies.
"""

# TASK: Normalize text categories and fix inconsistent spellings

# Strip spaces, lowercase, and fix typos in categorical columns
# 1. Clean 'channel'
if 'channel' in df.columns:
    df['channel'] = df['channel'].str.strip().str.lower()   # Using strip ensures extra white spaces are removed
    # Map common typos / variations to standard values
    channel_map = {
        'atm': 'atm',
        'atM': 'atm',
        ' web': 'web',
        'web': 'web',
        'weeb': 'web',
        'mobile': 'mobile',
        'mobille': 'mobile',
        ' mobile': 'mobile',
        'unknown': 'unknown'
    }
    df['channel'] = df['channel'].map(lambda x: channel_map.get(x, 'unknown'))

# 2. Clean 'source_currency'
if 'source_currency' in df.columns:
    df['source_currency'] = df['source_currency'].str.strip().str.upper()
    # Already clean, but let's ensure uppercase consistency
    allowed_src = ['USD', 'CAD', 'GBP']
    df['source_currency'] = df['source_currency'].apply(lambda x: x if x in allowed_src else 'USD')

# 3. Clean 'dest_currency'
if 'dest_currency' in df.columns:
    df['dest_currency'] = df['dest_currency'].str.strip().str.upper()
    allowed_dest = ['CAD', 'MXN', 'CNY', 'EUR', 'INR', 'GBP', 'PHP', 'NGN', 'USD']
    df['dest_currency'] = df['dest_currency'].apply(lambda x: x if x in allowed_dest else 'USD')

# 4. Clean 'kyc_tier'
if 'kyc_tier' in df.columns:
    df['kyc_tier'] = df['kyc_tier'].str.strip().str.lower()
    # Map common typos to standard tiers
    kyc_map = {
        'standard': 'standard',
        'standrd': 'standard',
        'enhanced': 'enhanced',
        'enhancd': 'enhanced',
        'low': 'low',
        'unknown': 'unknown'
    }
    df['kyc_tier'] = df['kyc_tier'].map(lambda x: kyc_map.get(x, 'unknown'))

# Check unique values after cleaning
print("Unique channels:", df['channel'].unique())
print("Unique source currencies:", df['source_currency'].unique())
print("Unique destination currencies:", df['dest_currency'].unique())
print("Unique KYC tiers:", df['kyc_tier'].unique())

# UPDATE UNKNOWN TO NAN

# Columns to update
cols_to_update = ['channel', 'kyc_tier']

for col in cols_to_update:
    if col in df.columns:
        df[col] = df[col].replace('unknown', np.nan)

# Check unique values after conversion
for col in cols_to_update:
    print(f"Unique values in {col} after conversion:", df[col].unique())

# CHECK FOR THE SUM OF THE 'NaN' MISSING VALUES
df.isna().sum()

df.dropna(inplace = True)  # Values are negligible

df.isna().sum()

# Done

# Save cleaned dataset
output_path = "cleaned_transactions.csv"
df.to_csv(output_path, index=False)

print(f"Cleaned dataset saved to {output_path}")

from google.colab import files
files.download("cleaned_transactions.csv")  # Download dataset

# Load cleaned dataset

df = pd.read_csv("cleaned_transactions.csv", parse_dates=['timestamp'])

df.head()

df.shape
df.info()
df.describe()

fraud_counts = df['is_fraud'].value_counts()

print(fraud_counts)

sns.countplot(x='is_fraud', data=df)
plt.title("Fraud vs Legitimate Transactions")
plt.show()

fraud_rate = df['is_fraud'].mean()
print(f"Fraud Rate: {fraud_rate:.2%}")

"""The above analysis shows that the dataset exhibits severe class imbalance, with fraudulent transactions representing only ~9% of all records.

###EXPLORATORY DATA ANALYSES AND FEATURE ENGINEERING

###Exploratory Data Analyses
####Bivariate EDA
This stage focuses on exploring how fraud differs from legitimate activity across each variables.

####Fraud vs Categorical Features
"""

# SELECT CATEGORICAL COLUMNS AND VISUALISE BY FRAUD RATE
cat_cols = ['channel','kyc_tier','home_country','source_currency','location_mismatch', 'dest_currency']

for col in cat_cols:
    fraud_rate = df.groupby(col)['is_fraud'].mean().sort_values(ascending=False)

    fraud_rate.plot(kind='bar', figsize=(8,4))
    plt.title(f"Fraud Rate by {col}")
    plt.show()

df["home_country"].unique()

df['home_country'].value_counts()

"""From observation, the home_country column contains formatting inconsistencies due to trailing spaces and mixed casing (e.g., "US " and "us"). These were standardized by stripping whitespace and converting values to lowercase. The "unknown" category was treated as missing data and converted to NaN and dropped to avoid introducing non-informative categories into the analysis."""

# Remove extra spaces
df['home_country'] = df['home_country'].str.strip()

# Standardize case (all to lower cases)
df['home_country'] = df['home_country'].str.lower()

# Convert unknown to NaN
df['home_country'] = df['home_country'].replace('unknown', np.nan)

df['home_country'].value_counts(dropna=False)

df = df.dropna(subset=['home_country'])    # Drop missing values since it's quite negligible

# Verify clean categories

df['home_country'].value_counts()

fraud_rate = df.groupby('home_country')['is_fraud'].mean().sort_values(ascending=False)

print(fraud_rate)

# REVERIFY FRAUD RATE BY HOME COUNTRY AGAIN

fraud_rate.plot(kind='bar', figsize=(6,4))
plt.title("Fraud Rate by Home Country")
plt.ylabel("Fraud Rate")
plt.xlabel("Home Country")
plt.show()

# Ensure all categorical variables are strings and lowercase
for col in cat_cols:
    # Convert to string first (handles booleans/numerics) and then lowercase
    df[col] = df[col].astype(str).str.lower()

# Verify unique values to check consistency
for col in cat_cols:
    print(f"{col} unique values:", df[col].unique())

# SANITY CHECK TO UNDERSTAND ACTUAL FRAUD RATE AND PROPORTIONS

# INFORMS RISK SCORING AND BETTER DECISION MAKING DOWNSTREAM
cat_cols = ['channel','kyc_tier','home_country','source_currency','location_mismatch','dest_currency']

for col in cat_cols:

    fraud_table = df.groupby(col).agg(
        transactions=('is_fraud','count'),
        fraud_cases=('is_fraud','sum')
    ).sort_values(by='fraud_cases', ascending=False)

    fraud_table['fraud_rate_%'] = (fraud_table['fraud_cases'] / fraud_table['transactions']) * 100
    fraud_table['proportion_%'] = (fraud_table['transactions'] / len(df)) * 100

    print(f"\nFraud Distribution for: {col}")
    display(fraud_table)

"""####Categorical Feature Fraud Insights

The the above categorical feature EDA analyses reveals several structural patterns distinguishing fraudulent from legitimate transactions:

- Transaction Channel: Web transactions show the highest fraud rate (~16.5%), compared to mobile (~4.7%) and ATM (~8.1%), indicating higher vulnerability in browser-based channels.

- KYC Verification Level: Low KYC accounts exhibit extremely high fraud exposure (~51%), while standard (~5%) and enhanced (~2.2%) tiers show significantly lower fraud risk, highlighting the importance of strong identity verification.

- Geographic Origin & Source Currency: Transactions from Canada and the UK (CAD, GBP) demonstrate higher fraud rates (~13–15%) compared to US-based transactions (~6.8%), suggesting corridor-specific fraud tendencies.

- Location Mismatch: Transactions with device-location mismatch show a very high fraud rate (~36%), compared to ~3.6% when locations match, making this one of the strongest fraud indicators.

- The categorical feature analysis reveals several structural patterns distinguishing fraudulent from legitimate transactions:

- Transaction Channel: Web transactions show the highest fraud rate (~16.5%), compared to mobile (~4.7%) and ATM (~8.1%), indicating higher vulnerability in browser-based channels.

- KYC Verification Level: Low KYC accounts exhibit extremely high fraud exposure (~51%), while standard (~5%) and enhanced (~2.2%) tiers show significantly lower fraud risk, highlighting the importance of strong identity verification.

- Geographic Origin & Source Currency: Transactions from Canada and the UK (CAD, GBP) demonstrate higher fraud rates (~13–15%) compared to US-based transactions (~6.8%), suggesting corridor-specific fraud tendencies.

Overall, these findings indicate that KYC verification level, location mismatch, transaction channel, and specific international currency corridors are key categorical indicators of fraud risk and should be prioritized during feature engineering and modelling.

####Fraud vs Numerical Features
"""

# SELECT NUMERICAL COLUMNS
num_cols = [
    'amount_src',
    'amount_usd',
    'fee',
    'exchange_rate_src_to_dest',
    'ip_risk_score',
    'account_age_days',
    'device_trust_score',
    'chargeback_history_count',
    'risk_score_internal',
    'txn_velocity_1h',
    'txn_velocity_24h',
    'corridor_risk'
]

fraud_comparison = df.groupby('is_fraud')[num_cols].mean().T

fraud_comparison

# VISUALISE FRAUD VS NON FRAUD HEATMAP

plt.figure(figsize=(8,5))

sns.heatmap(
    fraud_comparison,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Fraud vs Non-Fraud Feature Comparison")

plt.show()

# CHECK CORRELATIONS
df[num_cols + ['is_fraud']].corr()['is_fraud'].sort_values(ascending=False)

"""####Numerical Feature Fraud Insights

The above comparative analyses of numerical features between fraudulent and legitimate transactions revealed strong behavioral differences. Fraudulent transactions display significant higher transaction velocities (txn_velocity_1h and txn_velocity_24h), elevated IP risk scores, with all evidently showing strong positive correlations and substantially lower device trust scores. They also tend to involve larger transaction amounts (amount_src and amount_usd). In contrast, legitimate transactions are associated with older account ages and higher fees, evidently showing strong negative correlation with fraudulent activities. These patterns highlights that behavioral metrics, device/IP risk indicators, transaction magnitude, and corridor-specific anomalies are strong predictors of fraud and should be prioritized as key indicators for our predictive model.
"""

#  DESCRIPTIVE ANALYSIS FOR ALL NUMERICAL COLUMNS (TO SPOT ANOMALIES AND OUTLIERS AND IDENTIFY PATTERNS)

num_cols = df.select_dtypes(include=['float64','int64']).columns

df[num_cols].describe()

"""###Observational Insights from Descriptive Statistics (Pre-Cleaning)

####A review of key numeric features above reveals strong skewness and behavioral patterns indicative of fraud:

1. Transaction Amounts (amount_src, amount_usd) – Median values (~160) are far below the means (~442–447), with max exceeding 12,000, showing extreme high-value transactions. These spikes may represent high-risk or anomalous activity.

2. Fees (fee) – Median fee (~3.5) contrasts sharply with a maximum near 10,000, suggesting rare outlier fees or data errors.

3. Exchange Rates (exchange_rate_src_to_dest, implied_rate) – Most transactions fall within reasonable FX ranges, but extreme maxima indicate potential misreported or edge-case conversions.

4. Behavioral & Risk Features (ip_risk_score, device_trust_score, txn_velocity_1h, txn_velocity_24h, chargeback_history_count, risk_score_internal, corridor_risk) – Medians are near zero, but maxima are substantial. Fraud is concentrated in high-velocity transactions, elevated IP risk scores, and low device trust, reinforcing the predictive value of these features.

5. Account Age (account_age_days) – Skewed toward newer accounts (median ~287), with fraudulent activity more likely in recently created accounts.

6. Fraud Indicator (is_fraud) – As already confirmed, only ~9% of transactions are fraudulent, indicating a highly imbalanced dataset, which will require appropriate data imbalance handling downstream - employing SMOTE technique.
"""

# HANDLING DATA SKEWNESS ISSUE

cap_dict = {
    'amount_src': df['amount_src'].quantile(0.99),
    'amount_usd': df['amount_usd'].quantile(0.99),
    'fee': df['fee'].quantile(0.99),
    'exchange_rate_src_to_dest': 5.0,
    'txn_velocity_1h': df['txn_velocity_1h'].quantile(0.99),
    'txn_velocity_24h': df['txn_velocity_24h'].quantile(0.99),
    'chargeback_history_count': df['chargeback_history_count'].quantile(0.99),
    'ip_risk_score': 1.0,
    'device_trust_score': 1.0,
    'risk_score_internal': 1.0,
    'corridor_risk': 1.0
}

for col, cap in cap_dict.items():
    df[col] = np.where(df[col] > cap, cap, df[col])



# FLOOR IMPOSSIBLE VALUES

floor_cols = [
    'amount_src','amount_usd','fee',
    'txn_velocity_1h','txn_velocity_24h',
    'chargeback_history_count','account_age_days'
]

for col in floor_cols:
    df[col] = np.where(df[col] < 0, 0, df[col])


# VERIFY CHANGES

df[num_cols].describe()

"""### Observational Insights from Descriptive Statistics (Clean)

####Transaction Amounts (amount_src, amount_usd)

- Median values (~$160) are much lower than the 99th percentile capped max (~$9,994), indicating highly skewed transaction distributions.

- Outlier capping reduced extreme distortions without losing meaningful high-value fraud signals.

####Fees (fee)

- Median fee is low at approx $3.5 with rare extreme values at approx $152 now capped

####Exchange Rates (exchange_rate_src_to_dest)

- Capped at 5, reflecting realistic currency conversions.

- Protects against erroneous or maliciously manipulated rates.

####Behavioural Metrics (txn_velocity_1h, txn_velocity_24h)

- Velocities are mostly zero, but extreme behaviours are flagged (high_txn_velocity_1h, high_txn_velocity_24h).

- Critical predictive signals for fraud, capturing burst transaction patterns (featured downstream).

####Device/IP Risk (ip_risk_score, device_trust_score)

- Median IP risk ~0.325, median device trust ~0.658.

- Flags for high_ip_risk and low_device_trust enhance detection of suspicious sessions.

####Account Age (account_age_days)

- Median ~288 days; low-age accounts remain as potential high-risk indicators.
"""

# FURTHER SANITY CHECK (ALSO TO INFORM DOWNSTREAM RISK SCORING)

# Splits numerical features into quantile bins (q=4) and computes fraud statistics (using transactions, fraud cases, fraud rate)
# within each bin to observe how fraud risk changes across different value ranges of each numerical variable.

fraud_analysis = {}

for col in num_cols:

    if col != 'is_fraud':   # skip target variable

        # create quantile bins
        df[col + '_bin'] = pd.qcut(df[col], q=4, duplicates='drop')

        # compute fraud statistics
        fraud_table = df.groupby(col + '_bin').agg(
            transactions=('is_fraud','count'),
            fraud_cases=('is_fraud','sum'),
            fraud_rate=('is_fraud','mean')
        )

        fraud_table['fraud_rate'] = fraud_table['fraud_rate'] * 100

        fraud_analysis[col] = fraud_table

        print(f"\nFraud Distribution for: {col}")
        display(fraud_table)

"""Further Observational EDA Insights

The analysis reveals clear fraud concentration patterns, where fraud probability rises sharply beyond specific behavioral thresholds.

1. Transaction Value & Fees:
Higher transaction amounts (>$300) and fees (>$5.56) show fraud rates above 25%, indicating fraudsters often attempt large-value extractions once access is obtained.

2. IP Risk:
Transactions from IP risk scores above 0.49 exhibit nearly 30% fraud, highlighting the role of suspicious infrastructure such as VPNs or proxy networks.

3. Account Age:
Accounts younger than 147 days show about 28% fraud, while older accounts maintain rates near 1%, suggesting fraud is concentrated among new or compromised accounts.

4. Device Trust:
Low device trust (<0.52) corresponds to ~29% fraud, compared to <1% for highly trusted devices, underscoring the importance of device reputation signals.

5. Internal Risk Score:
Transactions with internal risk scores above 0.39 show nearly 38% fraud, confirming that the behavioral risk engine effectively captures anomalies.

6. Transaction Corridor Risk:
Higher corridor risk (>0.05) shows ~19.6% fraud, indicating that certain transaction routes are historically more vulnerable.

Overall, this further analysis provides a solid basis for our targeted risk scoring and feature engineering downstream.
"""

# TEMPORAL FORMATTING
# Extract hour, weekday, weekend
df['hour'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek
df['is_weekend'] = df['day_of_week'].isin([5,6]).astype(int)

# Extract month and quarter
df['month'] = df['timestamp'].dt.month
df['quarter'] = df['timestamp'].dt.quarter

# Map month numbers to names
month_map = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr',
             5:'May', 6:'Jun', 7:'Jul', 8:'Aug',
             9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}
df['month_name'] = df['month'].map(month_map)

# Map quarter numbers to labels
quarter_map = {1:'Q1', 2:'Q2', 3:'Q3', 4:'Q4'}
df['quarter_label'] = df['quarter'].map(quarter_map)

# GET SPECIFIC SUMMARY ACROSS TEMPORAL PATTERNS IN ORDER TO UNDERSTAND;
# whether time-based transaction patterns provide meaningful predictive signals for fraud detection

# Function to summarize temporal fraud
def temporal_fraud_summary_ordered(df, col, order=None):
    summary = df.groupby(col)['is_fraud'].agg(['count','sum']).rename(
        columns={'count':'transactions','sum':'fraud_cases'}
    )
    summary['fraud_rate_%'] = (summary['fraud_cases'] / summary['transactions']) * 100
    summary['proportion_%'] = (summary['transactions'] / df.shape[0]) * 100

    if order:  # Reindex
        summary = summary.reindex(order)
    return summary

# Map numeric day_of_week to names for readability
day_map = {0:'Mon', 1:'Tue', 2:'Wed', 3:'Thu', 4:'Fri', 5:'Sat', 6:'Sun'}
df['day_name'] = df['day_of_week'].map(day_map)

# Temporal summaries

# Hourly fraud summary (0-23)
hourly_fraud_summary = temporal_fraud_summary_ordered(df, 'hour', order=range(0,24))

# Weekday fraud summary (Mon-Sun)
weekday_order = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
weekday_fraud_summary = temporal_fraud_summary_ordered(df, 'day_name', order=weekday_order)

# Monthly fraud summary (Jan-Dec)
monthly_order = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
monthly_fraud_summary = temporal_fraud_summary_ordered(df, 'month_name', order=monthly_order)

# Quarterly fraud summary (Q1-Q4)
quarter_order = ['Q1','Q2','Q3','Q4']
quarterly_fraud_summary = temporal_fraud_summary_ordered(df, 'quarter_label', order=quarter_order)

# Display summaries
display(hourly_fraud_summary)
display(weekday_fraud_summary)
display(monthly_fraud_summary)
display(quarterly_fraud_summary)

# VISUALISE TEMPORAL PLOTS BY FRAUD RATE

# Hourly Fraud Rate
hourly_fraud = df.groupby('hour')['is_fraud'].mean()
hourly_fraud.plot(kind='line', marker='o')
plt.title("Fraud Rate by Hour of Day")
plt.show()

# Weekly Fraud Rate
weekday_fraud = df.groupby('day_of_week')['is_fraud'].mean()
weekday_fraud.plot(kind='bar')
plt.title("Fraud Rate by Day of Week")
plt.show()

# Monthly Fraud Rate
monthly_fraud_summary['fraud_rate_%'].plot(kind='bar')
plt.title("Fraud Rate by Month")
plt.show()

# Quarterly
quarterly_fraud_summary['fraud_rate_%'].plot(kind='bar')
plt.title("Fraud Rate by Quarter")
plt.show()

"""####From the EDA performed above, it can be deduced that:

hour → strong predictor, large variance (4–21% fraud rate) with a spike from around 3 AM to 8 AM

month → moderate predictor, some seasonal signal (7.7–10.6%)

day_of_week → weak predictor, little variation (8–10%)

quarter → weak predictor, minimal variation (8.3–9.5%)

Therefore, the subsequent analysis prioritizes only the hour-based temporal features for feature engineering and downstream modeling, ensuring the model focuses on the most informative time-related fraud patterns.
"""

def compute_risk_scores(df):
    """
    Compute behavioral and temporal risk scores using only
    features with correlation >= 0.15 with is_fraud.
    """

    # TEMPORAL RISK
    df['high_risk_hour'] = df['hour'].between(0, 8).astype(int)

    # AMOUNT & TRANSACTION BEHAVIOUR
    df['high_amount'] = (df['amount_usd'] > 300).astype(int)
    df['high_txn_velocity_1h'] = (df['txn_velocity_1h'] >= 3).astype(int)
    df['high_txn_velocity_24h'] = (df['txn_velocity_24h'] >= 5).astype(int)

    # ACCOUNT & INFRASTRUCTURE RISK
    df['high_ip_risk'] = (df['ip_risk_score'] > 0.49).astype(int)
    df['low_device_trust'] = (df['device_trust_score'] < 0.52).astype(int)
    df['new_account'] = (df['account_age_days'] < 147).astype(int)
    df['high_corridor_risk'] = (df['corridor_risk'] > 0.05).astype(int)

    # GEOGRAPHIC RISK
    df['high_risk_channel'] = df['channel'].str.lower().isin(['web']).astype(int)
    df['high_risk_kyc'] = df['kyc_tier'].str.lower().isin(['low']).astype(int)

    df['high_risk_location_mismatch'] = df['location_mismatch'].apply(
        lambda x: 1 if str(x).lower() == 'true' else 0
    )

    df['high_risk_dest_currency'] = df['dest_currency'].str.lower().isin(
        ['ngn','mxn','inr','php']
    ).astype(int)

    # FEATURES USED
    risk_features = [
        'high_txn_velocity_1h',
        'high_txn_velocity_24h',
        'new_account',
        'high_risk_kyc',
        'high_ip_risk',
        'high_risk_location_mismatch',
        'low_device_trust',
        'high_amount',
        'high_corridor_risk',
        'high_risk_channel',
        'high_risk_dest_currency',
        'high_risk_hour'
    ]

        # COMPOSITE BEHAVIORAL SCORE
    df['behavioral_risk_score'] = df[risk_features].sum(axis=1)
    df['normalized_behavioral_risk'] = df['behavioral_risk_score'] / len(risk_features)

    # RISK LEVEL CATEGORIES

    df['risk_level'] = pd.cut(
        df['normalized_behavioral_risk'],
        bins=[-0.01,0.2,0.4,0.6,1],
        labels=['Low Risk','Moderate Risk','Elevated Risk','High Risk']
    )
    return df
df = compute_risk_scores(df)

# Generate Risk Summary
risk_summary = df.groupby('risk_level').agg(
    transactions=('is_fraud','count'),
    fraud_cases=('is_fraud','sum')
).reset_index()

# Calculate fraud rate and proportion
risk_summary['fraud_rate_%'] = (risk_summary['fraud_cases'] / risk_summary['transactions']) * 100
risk_summary['proportion_%'] = (risk_summary['transactions'] / len(df)) * 100

# Optional: sort by risk severity
risk_summary = risk_summary.sort_values(by='risk_level', ascending=True).reset_index(drop=True)

# Display the table
print(risk_summary)

"""####ANALYTICAL RATIONALE FOR ENGINEERED RISK INDICATORS

The composite behavioral risk score combines multiple fraud indicators reflecting transaction behavior, account and infrastructure risk, and contextual anomalies. Each binary feature signals a potential fraud pattern identified during EDA, such as unusually high transaction amounts, low device trust, elevated IP risk, or rapid transaction bursts. By aggregating these into a single score and stratifying into Low, Moderate, Elevated, and High Risk categories, we observe that high-risk transactions exhibit an extremely elevated fraud rate (~99%), got 99 first while Low and Moderate Risk transactions have minimal fraud exposure (<3%). This demonstrates that the model effectively captures the cumulative impact of multiple suspicious signals, providing a robust and interpretable metric for fraud detection.
"""

# VISUALISE BEHAVIOURAL RISK OBSERVATION

sns.barplot(x=risk_summary.index, y=risk_summary['fraud_rate_%'])
plt.title('Fraud Rate by Behavioral Risk Level')
plt.ylabel('Fraud Rate (%)')
plt.xlabel('Risk Level')
plt.show()

# VERIFY EACH RISK FEATURE CORRELATION WITH FRAUD

risk_features = [
    'high_txn_velocity_1h',
    'high_txn_velocity_24h',
    'new_account',
    'high_risk_kyc',
    'high_ip_risk',
    'high_risk_location_mismatch',
    'low_device_trust',
    'high_amount',
    'high_corridor_risk',
    'high_risk_channel',
    'high_risk_dest_currency',
    'high_risk_hour'
    ]

df[risk_features + ['is_fraud']].corr()['is_fraud'].sort_values(ascending=False)

"""#### DEEPER ANALYTICAL INSIGHTS
The above correlation analysis across each synthetic risk indicators shows that transaction velocity features (high_txn_velocity_1h, high_txn_velocity_24h) are the strongest predictors of fraud, followed by chargeback risk, new accounts, low KYC verification, and infrastructure risks such as IP risk, location mismatch, and low device trust. In contrast, temporal and geographic features show weaker associations, indicating that behavioral activity patterns and customer risk history are the most influential drivers of fraud detection.
"""

df.isnull().sum()  # Check for missing values

# CHECK DATA INFORMATION
df.shape
df.info()
df.describe()

# NEXT: FURTHER FEATURE ENGINEERING PROCESS INCLUDING CONSTRUCTING OTHER RELEVANT FEATURES AND DEFINING INTERACTION FEATURES

def engineer_features(df):
    """
    NOVA Pay Fraud Feature Engineering (Optimized for ML + Business Obj)

    Focus:
    - Behavioral patterns (velocity, anomalies)
    - Relative deviations
    - Customer/device intelligence
    - High-signal interactions only
    """

    df = df.copy()

    # CUSTOMER BEHAVIOR AGGREGATES

    df['customer_txn_count'] = df.groupby('customer_id')['amount_usd'].transform('count')
    df['customer_avg_amount'] = df.groupby('customer_id')['amount_usd'].transform('mean')
    df['customer_total_amount'] = df.groupby('customer_id')['amount_usd'].transform('sum')

    # Customer corridor diversity
    df['customer_corridor_diversity'] = df.groupby('customer_id')['dest_currency'].transform('nunique')


    # ANOMALY FEATURES

    # Transaction velocity ratio
    df['txn_ratio_1h_24h'] = df['txn_velocity_1h'] / (df['txn_velocity_24h'] + 1)

    # Chargeback risk bucket
    df['chargeback_risk'] = pd.cut(
        df['chargeback_history_count'],
        bins=[-1,0,1,100],
        labels=[0,1,2]
    ).astype(int)


    #  HIGH-SIGNAL INTERACTIONS &  FRAUD PATTERN FEATURES

    df['velocity_24h_amount_interaction'] = df['txn_velocity_24h'] * df['amount_usd']

    df['ip_device_interaction'] = df['high_ip_risk'] * df['low_device_trust']

    df['chargeback_amount_interaction'] = df['chargeback_risk'] * df['amount_usd']

    df['new_corridor_flag'] = (
        df.groupby(['customer_id', 'dest_currency'])['dest_currency']
        .transform('count') == 1
    ).astype(int)

    return df

# APPLY FUNCTIONS

df = compute_risk_scores(df)
df = engineer_features(df)

print("Columns in final dataset:", df.columns.tolist())
display(df.head())

"""####Feature Engineering Rationale

We transformed the raw transaction data into meaningful features that help the model spot fraud more effectively. Customer aggregates show normal behavior patterns, making it easier to detect unusual activity in transaction amounts, frequency, or transfer corridors. Temporal and infrastructure signals—like high-risk hours, device trust, IP risk, account age, and transaction velocity—capture behaviors often linked to fraud. Interaction features highlight cases where multiple risk signals appear together.

The composite behavioral risk score combines these signals into a single, interpretable measure of risk, helping stratify transactions from low to high risk. Overall, these engineered features will give the model richer insights into customer behavior and transaction context, thereby improving fraud detection while keeping the system interpretable and ready for deployment.
"""

missing_features = [f for f in risk_features if f not in df.columns]

print("Missing features:", missing_features)

corr_results = df[risk_features + ['is_fraud']].corr()['is_fraud'].sort_values(ascending=False)

display(corr_results)

engineered_features = [

    # CUSTOMER BEHAVIOR
    'customer_txn_count',
    'customer_avg_amount',
    'customer_total_amount',
    'customer_corridor_diversity',

    # BEHAVIORAL / VELOCITY
    'txn_ratio_1h_24h',

    # INTERACTIONS (STRONG SIGNAL)
    'velocity_24h_amount_interaction',
    'ip_device_interaction',
    'chargeback_amount_interaction',

    # FRAUD PATTERN
    'new_corridor_flag'
]
engineered_corr = df[engineered_features + ['is_fraud']].corr()['is_fraud'].sort_values(ascending=False)

display(engineered_corr)

"""#### MODEL DATA PREPARATION"""

from sklearn.preprocessing import StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
def prepare_model_data(df, target_col='is_fraud', time_col='timestamp', train_ratio=0.8):

    df[time_col] = pd.to_datetime(df[time_col])
    df = df.sort_values(time_col)

    feature_cols = [
        'normalized_behavioral_risk',
        'high_txn_velocity_1h', 'high_txn_velocity_24h',
        'velocity_24h_amount_interaction', 'ip_device_interaction',
        'customer_txn_count', 'customer_total_amount', 'customer_corridor_diversity',
        'customer_avg_amount', 'chargeback_amount_interaction', 'txn_ratio_1h_24h',
        'new_corridor_flag', 'device_count_per_customer', 'high_ip_risk',
        'new_account', 'high_risk_score', 'high_risk_hour'
    ]

    available_features = [f for f in feature_cols if f in df.columns]

    # Time-based split
    cutoff = int(len(df) * train_ratio)
    train_df = df.iloc[:cutoff]
    test_df = df.iloc[cutoff:]

    X_train = train_df[available_features].copy()
    y_train = train_df[target_col].copy()
    X_test = test_df[available_features].copy()
    y_test = test_df[target_col].copy()

    # Encoding
    categorical_cols = [
        'new_corridor_flag', 'high_txn_velocity_1h', 'high_txn_velocity_24h',
        'high_ip_risk', 'new_account', 'high_risk_score', 'high_risk_hour'
    ]

    encoders = {}
    for col in categorical_cols:
        if col in X_train.columns:
            le = LabelEncoder()
            X_train[col] = le.fit_transform(X_train[col].astype(str))
            X_test[col] = le.transform(X_test[col].astype(str))
            encoders[col] = le

    # Scaling
    numeric_cols = [
        'customer_txn_count', 'customer_total_amount', 'customer_corridor_diversity',
        'customer_avg_amount', 'device_count_per_customer',
        'velocity_24h_amount_interaction', 'txn_ratio_1h_24h',
        'chargeback_amount_interaction', 'normalized_behavioral_risk'
    ]
    numeric_cols = [c for c in numeric_cols if c in X_train.columns]

    scaler = StandardScaler()
    X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
    X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

    # SMOTE (for comparison later)
    smote = SMOTE(random_state=42)
    X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

    print("Original train:", X_train.shape, "Fraud ratio:", y_train.mean())
    print("SMOTE train:", X_train_bal.shape, "Fraud ratio:", y_train_bal.mean())

    return X_train, X_train_bal, X_test, y_train, y_train_bal, y_test, scaler, encoders, available_features

X_train, X_train_bal, X_test, y_train, y_train_bal, y_test, scaler, encoders, features_used = prepare_model_data(df,
                                                                                                       target_col='is_fraud',
                                                                                                       time_col='timestamp')
# Check class distribution after SMOTE
print("Training data after SMOTE:")
print(f"Shape: {X_train_bal.shape}")
print(f"Fraud ratio: {y_train_bal.mean():.4f}")

print("\nTest data (real distribution, no SMOTE):")
print(f"Shape: {X_test.shape}")
print(f"Fraud ratio: {y_test.mean():.4f}")

# Display sample of training features after SMOTE
print("\nSample training features after SMOTE:")
display(X_train_bal.head())

# Inspect which features are being used
print("\nFeatures used for modeling:")
print(features_used)

"""Fraud Ratios

Original training fraud ratio: 0.091 (~9%) → Indicates high class imbalance, typical for fraud datasets.

After SMOTE fraud ratio: 0.5 (50%) → SMOTE generated synthetic fraud cases to balance the training set, so models can better learn patterns without being biased toward non-fraud transactions.

Test set fraud ratio: 0.091 (~9%) → Remains realistic for evaluation; SMOTE is applied only to training data, avoiding data leakage.

#### MODEL DEVELOPMENT
"""

from sklearn.metrics import classification_report, roc_auc_score, precision_recall_curve, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb


# Logistic Regression
lr = LogisticRegression(max_iter=1000, random_state=42)

# Random Forest
rf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)

# XGBoost
xgb_model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

# Fit models on balanced training set
lr.fit(X_train_bal, y_train_bal)
rf.fit(X_train_bal, y_train_bal)
xgb_model.fit(X_train_bal, y_train_bal)

# Predict on the test set (i.e the real distribution)
y_pred_lr = lr.predict(X_test)
y_pred_rf = rf.predict(X_test)
y_pred_xgb = xgb_model.predict(X_test)

# Predict probabilities for ROC-AUC
y_prob_lr = lr.predict_proba(X_test)[:, 1]
y_prob_rf = rf.predict_proba(X_test)[:, 1]
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

# Evaluate model
def evaluate_model(name, model, X_test, y_test, feature_names=None):
    # Predict classes
    y_pred = model.predict(X_test)
    # Predict probabilities for ROC-AUC
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = model.decision_function(X_test)

    # Classification report (keep numeric labels)
    print(f"\n{name} Performance:")
    print(classification_report(y_test, y_pred, digits=4))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred, labels=[0,1])
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[0,1], yticklabels=[0,1])
    plt.title(f"{name} Confusion Matrix")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

    # Feature importance / coefficients
    if feature_names is not None:
        if hasattr(model, "feature_importances_"):  # For Tree-based
            importance = model.feature_importances_
        elif hasattr(model, "coef_"):  # For Logistic Regression
            importance = model.coef_[0]
        else:
            importance = None

        if importance is not None:
            fi = pd.DataFrame({
                'Feature': feature_names,
                'Importance': importance
            }).sort_values(by='Importance', ascending=False)
            print(f"\nTop Features for {name}:")
            display(fi.head(10))

# Evaluate Logistic Regression
evaluate_model("Logistic Regression", lr, X_test, y_test, feature_names=features_used)

# Evaluate Random Forest
evaluate_model("Random Forest", rf, X_test, y_test, feature_names=features_used)

# Evaluate XGBoost
evaluate_model("XGBoost", xgb_model, X_test, y_test, feature_names=features_used)

"""####Expected Output: Baseline Models Summary

Trained three baseline models: Logistic Regression, Random Forest, and XGBoost using a time-based split and SMOTE-balanced training data.

Evaluated models on the original imbalanced test set to reflect real-world performance.

Metrics used:

- Accuracy

- Precision, Recall, F1-score

- ROC-AUC

All models achieved strong performance:

- Accuracy: ~96.7% – 97.0%

- ROC-AUC: ~0.98 (excellent class separation)

- High recall and precision for the fraud class

Interpretability:

- Logistic Regression → coefficients was used to understand feature impact

- Random Forest & XGBoost → feature importance

####Feature Importance Analysis
Key Observations Across Models

- Normalized_behavioral_risk feature is the most important predictor across all models, confirming it as the strongest fraud signal.

- Transaction velocity features (high_txn_velocity_1h, velocity_24h_amount_interaction) consistently rank highly, indicating that rapid transaction behavior is a major fraud indicator.

Customer behavior metrics such as:

- customer_txn_count

- customer_total_amount

- customer_avg_amount are important across models, suggesting that deviations from normal user behavior help detect fraud.

####Fraud Risk Interpretation (Nova Pay Business View)

High fraud risk is associated with:

- Unusual transaction velocity

- High behavioral risk scores

- New or low-history accounts

- Large or abnormal transaction amounts

Lower fraud risk is associated with:

- Consistent and diverse transaction behavior

#### FIND THE BEST THRESHOLD
"""

from sklearn.metrics import precision_recall_curve, f1_score

def find_best_threshold(model, X_test, y_test, positive_label=1):
    # Get predicted probabilities for the positive class
    y_prob = model.predict_proba(X_test)[:, 1]

    # Get precision, recall, thresholds
    precision, recall, thresholds = precision_recall_curve(y_test, y_prob, pos_label=positive_label)

    # Compute F1 for each threshold
    f1_scores = 2 * (precision * recall) / (precision + recall + 1e-6)

    # Best threshold based on max F1
    best_idx = f1_scores.argmax()
    best_threshold = thresholds[best_idx]
    best_f1 = f1_scores[best_idx]
    best_precision = precision[best_idx]
    best_recall = recall[best_idx]

    print(f"Best threshold for {model.__class__.__name__}: {best_threshold:.3f}")
    print(f"Precision: {best_precision:.3f}, Recall: {best_recall:.3f}, F1: {best_f1:.3f}")

    return best_threshold, best_precision, best_recall, best_f1

# Test thresholds for all models
best_thresh_lr = find_best_threshold(lr, X_test, y_test)
best_thresh_rf = find_best_threshold(rf, X_test, y_test)
best_thresh_xgb = find_best_threshold(xgb_model, X_test, y_test)

"""####Optimal Probability Threshold

The default threshold of 0.5 was not optimal due to class imbalance in the test data.

Using precision-recall analysis, the best thresholds were identified as:

- Logistic Regression → 0.905

- Random Forest → 0.854

- XGBoost → 0.980

At these thresholds:

- Precision = 1.000 → no false positives

- Recall ≈ 0.919 → most fraud cases detected

- F1 ≈ 0.958 → strong balance

This shows that higher thresholds provide better control over false positives while maintaining high fraud detection rates.
"""

def plot_confusion(model, X_test, y_test, threshold, name):
    """
    Plots confusion matrix for a model at a given probability threshold.
    """
    # Predict with threshold
    y_pred_thresh = (model.predict_proba(X_test)[:,1] >= threshold).astype(int)

    # Compute confusion matrix
    cm = confusion_matrix(y_test, y_pred_thresh)

    # Plot heatmap
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False)
    plt.title(f"{name} Confusion Matrix\n(threshold={threshold:.3f})")
    plt.ylabel("Actual")
    plt.xlabel("Predicted")
    plt.xticks([0.5,1.5], ['Legit (0)', 'Fraud (1)'])
    plt.yticks([0.5,1.5], ['Legit (0)', 'Fraud (1)'], rotation=0)
    plt.show()

    # Also print numeric matrix
    print(f"\nConfusion Matrix for {name} (threshold={threshold:.3f}):\n", cm)

# Use the best thresholds you found earlier
plot_confusion(lr, X_test, y_test, best_thresh_lr[0], "Logistic Regression")
plot_confusion(rf, X_test, y_test, best_thresh_rf[0], "Random Forest")
plot_confusion(xgb_model, X_test, y_test, best_thresh_xgb[0], "XGBoost")

"""#### MODEL COMPARISON
#### Logistic Regression

Accuracy: 0.9671

ROC-AUC: 0.9843

Precision (Fraud): 0.8430 → improved to 1.000 after threshold tuning

Recall (Fraud): 0.9416 → slightly reduced to 0.919 after threshold tuning

Strong recall and competitive overall performance

Highly interpretable (clear feature impact via coefficients)

Performs well despite being a simpler linear model

####Random Forest

Accuracy: 0.9703 (highest among models)

ROC-AUC: 0.9814

Precision (Fraud): 0.8671 → improved to 1.000 after threshold tuning

Recall (Fraud): 0.9318 → slightly reduced to 0.919 after threshold tuning

Slightly better balance between precision and recall

Captures non-linear relationships effectively

Most stable performer across all evaluation metrics

#### XGBoost

Accuracy: 0.9676

ROC-AUC: 0.9796

Precision (Fraud): 0.8537 → improved to 1.000 after threshold tuning

Recall (Fraud): 0.9286 → slightly reduced to 0.919 after threshold tuning

Similar performance to Random Forest

Required a higher threshold (0.980), indicating more conservative probability estimates

Focusing on high-confidence fraud predictions

### Advanced Fraud Detection Model Experiments: LightGBM vs XGBoost

#### Tasks / Activities
- Train and evaluate **LightGBM** and **XGBoost** models.
- Experiment with **SMOTE**, **undersampling**, and **class-weight adjustments**.
- Compare results in a structured experiment log.

#### Reflection
- Investigate how **varying fraud prevalence over time** affects performance stability.

#### LightGBM Resampling Experiment
"""

def run_lgb_model(X_train, y_train, X_test, y_test, method_name, model_params=None):

    if model_params is None:
        model_params = {}

    model = lgb.LGBMClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        num_leaves=31,
        random_state=42,
        **model_params
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    report = classification_report(y_test, y_pred, output_dict=True)

    return {
        "Method": method_name,
        "Accuracy": report['accuracy'],
        "Precision_Fraud": report['1']['precision'],
        "Recall_Fraud": report['1']['recall'],
        "F1_Fraud": report['1']['f1-score'],
        "ROC_AUC": roc_auc_score(y_test, y_prob),
        "model": model,
        "y_prob": y_prob
    }

# Undersampling
rus = RandomUnderSampler(random_state=42)
X_under, y_under = rus.fit_resample(X_train, y_train)

# Experiments
results_base = run_lgb_model(X_train, y_train, X_test, y_test, "Baseline")
results_weighted = run_lgb_model(
    X_train, y_train, X_test, y_test,
    "Class Weights",
    model_params={"class_weight": "balanced"}
)
results_smote = run_lgb_model(
    X_train_bal, y_train_bal, X_test, y_test,
    "SMOTE"
)
results_under = run_lgb_model(
    X_under, y_under, X_test, y_test,
    "Undersampling"
)

# Results table
results_df = pd.DataFrame([
    results_base,
    results_weighted,
    results_smote,
    results_under
])

display(results_df[['Method','Accuracy','Precision_Fraud','Recall_Fraud','F1_Fraud','ROC_AUC']]
        .sort_values(by='F1_Fraud', ascending=False))

cm = confusion_matrix(y_test, (results_base['y_prob'] >= 0.5).astype(int))

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=[0,1], yticklabels=[0,1])
plt.title("Baseline LGB Confusion Matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()


precision, recall, thresholds = precision_recall_curve(y_test, results_base['y_prob'])

f1_scores = 2 * (precision * recall) / (precision + recall + 1e-9)
best_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_idx]

print(f"Best threshold: {best_threshold:.3f}")
print(f"Precision: {precision[best_idx]:.3f}")
print(f"Recall: {recall[best_idx]:.3f}")
print(f"F1: {f1_scores[best_idx]:.3f}")

plt.figure(figsize=(7,5))
plt.plot(recall, precision, label="Baseline LGB")
plt.scatter(recall[best_idx], precision[best_idx], color='red')
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

lgb_clf = results_base['model']

lgb_feat_imp = pd.DataFrame({
    "Feature": features_used,
    "Importance": lgb_clf.feature_importances_
}).sort_values(by='Importance', ascending=False)

display(lgb_feat_imp.head(10))

"""#### XGBoost Resampling Experiment"""

import xgboost as xgb

def run_xgb_experiment(X_train, y_train, X_test, y_test, method_name, model_params=None):
    if model_params is None:
        model_params = {}
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        random_state=42,
        eval_metric='logloss',
        **model_params
    )
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]
    report = classification_report(y_test, y_pred, output_dict=True)

    return {
        "Method": method_name,
        "Accuracy": report['accuracy'],
        "Precision_Fraud": report['1']['precision'],
        "Recall_Fraud": report['1']['recall'],
        "F1_Fraud": report['1']['f1-score'],
        "ROC_AUC": roc_auc_score(y_test, y_prob),
        "model": model,
        "y_prob": y_prob
    }

    from imblearn.under_sampling import RandomUnderSampler

# Prepare undersample
rus = RandomUnderSampler(random_state=42)
X_under, y_under = rus.fit_resample(X_train, y_train)

# Baseline
xgb_base = run_xgb_experiment(X_train, y_train, X_test, y_test, "Baseline")

# Class Weights (scale_pos_weight)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

xgb_weighted = run_xgb_experiment(
    X_train, y_train, X_test, y_test,
    "Class Weights",
    model_params={"scale_pos_weight": scale_pos_weight}
)

# SMOTE
xgb_smote = run_xgb_experiment(
    X_train_bal, y_train_bal, X_test, y_test,
    "SMOTE"
)

# Undersampling
xgb_under = run_xgb_experiment(
    X_under, y_under, X_test, y_test,
    "Undersampling"
)

xgb_results_df = pd.DataFrame([
    xgb_base,
    xgb_weighted,
    xgb_smote,
    xgb_under
])

display(
    xgb_results_df[
        ['Method','Accuracy','Precision_Fraud','Recall_Fraud','F1_Fraud','ROC_AUC']
    ].sort_values(by='F1_Fraud', ascending=False)
)

"""##  LightGBM Model Summary

- Evaluated under four strategies: **Baseline**, **SMOTE**, **Class Weights**, **Undersampling**.
- **Baseline LightGBM** achieved the best overall performance:
  - F1-score: **0.9529**
  - Precision (fraud): **0.9895**
  - Recall (fraud): **0.9188**
- Minimal improvement from SMOTE or class weighting, indicating:
  - Engineered features effectively capture fraud patterns.
  - LightGBM’s **leaf-wise growth** handles rare fraud cases naturally.
- Robust to changing fraud prevalence over time indicating stable deployment-ready model.

**LightGBM Results Table:**

| Method          | Accuracy  | Precision_Fraud | Recall_Fraud | F1_Fraud | ROC_AUC  |
|-----------------|-----------|----------------|--------------|----------|----------|
| Baseline        | 0.9872    | 0.9895         | 0.9188       | 0.9529   | 0.9774   |
| SMOTE           | 0.9626    | 0.8247         | 0.9318       | 0.8750   | 0.9789   |
| Class Weights   | 0.9470    | 0.7487         | 0.9383       | 0.8329   | 0.9764   |
| Undersampling   | 0.9274    | 0.6713         | 0.9481       | 0.7860   | 0.9778   |

---

##  XGBoost Model Summary

- Evaluated under same four strategies.
- **Baseline XGBoost** performed extremely well **without explicit tuning**:
  - F1-score: **0.9577**
  - Precision (fraud): **1.0000**
  - Recall (fraud): **0.9188**
- Performance remained stable across SMOTE and class-weight experiments.
- Slightly more sensitive to class imbalance compared to LightGBM:
  - This is because it requires `scale_pos_weight` or data balancing for extreme imbalance.

**XGBoost Results Table:**

| Method          | Accuracy  | Precision_Fraud | Recall_Fraud | F1_Fraud | ROC_AUC  |
|-----------------|-----------|----------------|--------------|----------|----------|
| Baseline        | 0.9886    | 1.0000         | 0.9188       | 0.9577   | 0.9786   |
| SMOTE           | 0.9676    | 0.8537         | 0.9286       | 0.8896   | 0.9796   |
| Class Weights   | 0.9461    | 0.7448         | 0.9383       | 0.8305   | 0.9775   |
| Undersampling   | 0.9393    | 0.7139         | 0.9481       | 0.8145   | 0.9791   |

---

##  Model Comparison: LightGBM vs XGBoost

| Feature / Aspect        | LightGBM                                     | XGBoost                                      |
|-------------------------|---------------------------------------------|---------------------------------------------|
| Tree Growth Strategy    | Leaf-wise: focuses on hardest cases first  | Level-wise: splits all nodes equally       |
| Handling Class Imbalance| Implicitly robust; handles rare fraud naturally | Needs `scale_pos_weight` or SMOTE          |
| Hyperparameter Sensitivity | Works well with defaults                  | Sensitive; tuning improves stability        |
| Adaptation to Time-varying Fraud | Stable; less affected by prevalence changes | Slightly sensitive; performance varies with imbalance |
| Speed & Efficiency      | Faster due to histogram-based binning       | Slower; exact/approx split computations    |
| Observed Performance    | Baseline very strong, minimal improvement from SMOTE | Baseline strong; minor gain from balancing |

---

### Key Insights/Reflection

- **LightGBM** is robust, fast, and stable out-of-the-box → ideal for dynamic fraud environments where fraud prevalence changes over time.
- **XGBoost** offers high flexibility and slightly better precision under baseline but is more sensitive to imbalance → tuning recommended for extreme scenarios.
- Both models detect fraud effectively, but **LightGBM provides a simpler, production-ready solution** due to its automatic handling of imbalanced classes and robustness across time.

> "LightGBM naturally prioritizes hard-to-classify fraud cases via its leaf-wise growth, while XGBoost requires careful guidance to focus on rare events."

#### MODEL EXPLAINABILITY (SHAP TECHNIQUE)
"""

import shap

print(f"SHAP version: {shap.__version__}")

# 1. Import SHAP
import shap

# 2. Use the TRAINED model (NOT the function)
lgb_clf = results_base['model']

explainer_lgb = shap.TreeExplainer(lgb_clf)

# 3. SHAP values
shap_values_lgb = explainer_lgb.shap_values(X_test[:100])

# 4. Plot
shap.summary_plot(
    shap_values_lgb,
    X_test[:100],
    feature_names=features_used,
    plot_type="bar"
)

reason_code_map = {
    "normalized_behavioral_risk": "High behavioural risk score",
    "high_txn_velocity_1h": "High transaction velocity (1 hour)",
    "high_txn_velocity_24h": "High transaction velocity (24 hours)",
    "velocity_24h_amount_interaction": "Unusual transaction volume and value pattern",
    "ip_device_interaction": "Suspicious device and IP combination",
    "customer_txn_count": "Unusual transaction frequency",
    "customer_total_amount": "High total transaction value",
    "customer_avg_amount": "Abnormal transaction size",
    "chargeback_amount_interaction": "Chargeback-related risk pattern",
    "txn_ratio_1h_24h": "Transaction velocity imbalance",
    "new_corridor_flag": "New transaction corridor detected",
    "device_count_per_customer": "Multiple devices used",
    "high_ip_risk": "High-risk IP address",
    "new_account": "Recently created account",
    "high_risk_score": "Elevated composite risk score",
    "high_risk_hour": "Transaction at high-risk time"
}

"""### Generate Review Template Using Test Data"""

def generate_review_template(idx, model, explainer, X_test, y_test, feature_names, threshold=0.5):

    # Prediction
    pred_proba = model.predict_proba(X_test.iloc[idx:idx+1])[0, 1]
    prediction = "FRAUD" if pred_proba >= threshold else "LEGITIMATE"
    true_label = "FRAUD" if y_test.iloc[idx] == 1 else "LEGITIMATE"

    # Risk level
    if pred_proba >= 0.8:
        risk_level = "HIGH"
    elif pred_proba >= 0.5:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    # Compute SHAP safely
    shap_vals = explainer.shap_values(X_test.iloc[idx:idx+1])

    # Handle LightGBM SHAP output format
    if isinstance(shap_vals, list):
        shap_vals = shap_vals[1][0]   # binary classification
    else:
        shap_vals = shap_vals[0]

    feature_vals = X_test.iloc[idx].values

    contributions = list(zip(feature_names, feature_vals, shap_vals))
    contributions.sort(key=lambda x: abs(x[2]), reverse=True)

    # Top drivers
    risk_factors = [c for c in contributions if c[2] > 0][:5]
    protective_factors = [c for c in contributions if c[2] < 0][:5]

    # Reason codes
    reason_codes = [
        reason_code_map.get(feat, feat)
        for feat, _, _ in risk_factors
    ]

    # Build report
    report = f"""
===============================
 FRAUD REVIEW TEMPLATE
===============================

Transaction ID: {idx}

Prediction: {prediction}
Confidence Score: {pred_proba:.2%}
Risk Level: {risk_level}

True Label: {true_label}

-------------------------------
 REASON CODES (Why flagged)
-------------------------------
"""

    for r in reason_codes:
        report += f" - {r}\n"

    report += "\n-------------------------------\n TOP RISK DRIVERS\n-------------------------------\n"

    for feat, val, shap_val in risk_factors:
        report += f" - {feat}: {val:.4f} (Impact: +{shap_val:.4f})\n"

    report += "\n-------------------------------\n PROTECTIVE FACTORS\n-------------------------------\n"

    for feat, val, shap_val in protective_factors:
        report += f" - {feat}: {val:.4f} (Impact: {shap_val:.4f})\n"

    return report

# TRANSACTION 33

print(generate_review_template(
    idx=33,
    model=results_base['model'],            # trained model
    explainer=explainer_lgb,                # SHAP explainer    
    X_test=X_test,
    y_test=y_test,
    feature_names=features_used
))

# TRANSACTION 34

print(generate_review_template(
    idx=34,
    model=results_base['model'],          
    explainer=explainer_lgb,              
    X_test=X_test,
    y_test=y_test,
    feature_names=features_used
))

# TRANSACTION 35

print(generate_review_template(
    idx=35,
    model=results_base['model'],        
    explainer=explainer_lgb,             
    X_test=X_test,
    y_test=y_test,
    feature_names=features_used
))

"""# NOVA PAY FRAUD DETECTION – FINAL REPORT

## 1. Objective

The objective of this project was to develop a robust fraud detection system that:
- Accurately identifies fraudulent transactions
- Maximizes fraud recall while minimizing false positives
- Provides transparent and explainable predictions
- Supports regulatory and operational decision-making

---

## 2. Approach Summary

We implemented a supervised machine learning classification framework using:

- LightGBM (Primary model)
- XGBoost (Benchmark model)

### Methodology:
- Time-based train/test split to reflect real-world fraud evolution
- Feature engineering focused on behavioral, velocity, and risk signals
- Evaluation on imbalanced test data (real-world distribution)
- Experimentation with:
  - Baseline (no balancing)
  - SMOTE
  - Class weighting
  - Undersampling
- SHAP used for transaction-level explainability

---

## 3. Model Performance Summary

### LightGBM (Primary Model)

- Accuracy: 0.9872
- Precision (Fraud): 0.9895
- Recall (Fraud): 0.9188
- F1 Score: 0.9529
- ROC-AUC: 0.9774

Insight:
LightGBM achieved the best balance between fraud detection and minimizing false positives, making it the most stable and production-ready model.

---

### XGBoost (Benchmark Model)

- Accuracy: 0.9886
- Precision (Fraud): 1.0000
- Recall (Fraud): 0.9188
- F1 Score: 0.9577
- ROC-AUC: 0.9786

Insight:
XGBoost achieved slightly higher precision but requires more tuning and monitoring for stability.

---

## 4. Key Fraud Drivers (Business Interpretation)

Key engineered features and their meanings:

- normalized_behavioral_risk → Overall customer risk profile
- high_txn_velocity_1h → Rapid transaction activity
- velocity_24h_amount_interaction → High spend combined with high frequency
- ip_device_interaction → Suspicious device and IP combination
- customer_txn_count → Transaction volume behavior
- customer_avg_amount → Typical spending behavior
- txn_ratio_1h_24h → Short-term spike vs long-term activity
- new_account → Recently created account
- high_ip_risk → Risky network source
- high_risk_hour → Late-night transactions (0–8 AM)

Insight:
Fraud is primarily driven by behavioral anomalies, transaction velocity, and new account activity.

---

## 5. Explainability (Model Transparency)

SHAP values were used to explain predictions at the transaction level.

Model decision logic:
Prediction = Base Risk + Sum of Feature Contributions

- Positive SHAP values push prediction toward fraud (top risk factors)
- Negative SHAP values push prediction toward legitimate (top protective factors)

---

## 6. Transaction-Level Analysis

### Transaction 34 (Correct Fraud Detection)

- Prediction: Fraud
- Confidence: 100%

Key Drivers:
- Extremely high behavioral risk
- New account
- High transaction velocity
- Suspicious IP/device interaction

Interpretation:
Multiple strong fraud indicators aligned, resulting in a high-confidence fraud prediction.

---

### Transaction 33 (False Negative – Missed Fraud)

- Prediction: Legitimate
- Confidence: 0.1%

Observed Behavior:
- Fraud signals present (velocity, unusual time/activity)
- Strong protective signals (stable behavior, normal patterns)

Insight:
The model prioritized long-term behavioral stability over short-term anomalies, leading to misclassification.

---

## 7. Error Analysis

- True Legitimate Transactions: 1879
- False Negatives: 25

Insight:
Missed fraud cases are rare but typically occur in subtle fraud scenarios embedded within normal behavior patterns as observed from the SHAP analysis.

---

## 8. Key Insights

Strengths:
- High accuracy and strong fraud detection performance
- Strong interpretability using SHAP
- Stable performance across time
- Minimal dependency on resampling techniques

Limitations:
- Difficulty detecting subtle or low-intensity fraud
- Over-reliance on aggregated behavioral features

---

## 9. NovaPay Business Impact

- Improved fraud detection accuracy
- Reduced false positives, improving customer experience
- Enhanced transparency for compliance and audit teams
- Faster fraud investigation through explainable outputs

---

## 10. Recommendations

- Introduce short-term anomaly detection features
- Implement adaptive thresholds
- Monitor model drift over time

---

## 11. Reflection

Fraud patterns evolve over time due to changing user behavior and attack strategies.

Key Finding:
LightGBM demonstrated strong stability across time and handled class imbalance effectively without requiring aggressive balancing techniques.

---

## 12. Conclusion

The project successfully delivered a high-performing, interpretable fraud detection system.

LightGBM emerged as the most robust and production-ready model, providing accurate predictions while maintaining transparency and business interpretability.
"""

import joblib
import os
import shap
from datetime import datetime

def save_fraud_artifacts(model, scaler, encoders, feature_names):

    print("\n" + "="*50)
    print("SAVING NOVAPAY FRAUD MODEL ARTIFACTS")
    print("="*50)

    # Create folder
    os.makedirs("artifacts", exist_ok=True)

    artifacts = {
        "model": model,
        "scaler": scaler,
        "encoders": encoders,
        "feature_names": list(feature_names),
        "version": "1.0",
        "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    # Save full pipeline
    joblib.dump(artifacts, "novapay_fraud_model.pkl")

    # Save individual components (for flexibility in API)
    joblib.dump(model, "artifacts/lgb_model.pkl")
    joblib.dump(scaler, "artifacts/scaler.pkl")
    joblib.dump(encoders, "artifacts/encoders.pkl")
    joblib.dump(feature_names, "artifacts/features.pkl")

    explainer = shap.TreeExplainer(model)
    joblib.dump(explainer, "artifacts/shap_explainer.pkl")

    print("\nArtifacts saved successfully:")
    print("• novapay_fraud_model.pkl")
    print("• artifacts/lgb_model.pkl")
    print("• artifacts/scaler.pkl")
    print("• artifacts/encoders.pkl")
    print("• artifacts/features.pkl")
    print("• artifacts/shap_explainer.pkl")

    print("="*50)

def novapay_pipeline(df):

    print("\n" + "="*60)
    print("NOVAPAY FRAUD DETECTION PIPELINE")
    print("="*60)

    # --------------------------------------------------
    # 1️⃣ Risk Scoring
    # --------------------------------------------------
    print("\n[1] Computing risk scores...")
    df = compute_risk_scores(df)

    # --------------------------------------------------
    # 2️⃣ Feature Engineering
    # --------------------------------------------------
    print("\n[2] Engineering features...")
    df = engineer_features(df)

    # --------------------------------------------------
    # 3️⃣ Data Preparation
    # --------------------------------------------------
    print("\n[3] Preparing model data...")
    X_train, X_train_bal, X_test, y_train, y_train_bal, y_test, scaler, encoders, features = prepare_model_data(df)

    # --------------------------------------------------
    # 4️⃣ Train Final Model (Baseline LightGBM)
    # --------------------------------------------------
    print("\n[4] Training final LightGBM model...")
    results = run_lgb_model(X_train, y_train, X_test, y_test, "Baseline")

    model = results["model"]

    print("\nModel Performance:")
    print(f"Accuracy: {results['Accuracy']:.4f}")
    print(f"F1 Score (Fraud): {results['F1_Fraud']:.4f}")
    print(f"ROC-AUC: {results['ROC_AUC']:.4f}")

    # --------------------------------------------------
    # 5️⃣ SHAP Explainability
    # --------------------------------------------------
    print("\n[5] Creating SHAP explainer...")

    # --------------------------------------------------
    # 6️⃣ Save Artifacts
    # --------------------------------------------------
    print("\n[6] Saving artifacts...")
    save_fraud_artifacts(model, scaler, encoders, features)

    print("\n" + "="*60)
    print("PIPELINE COMPLETED SUCCESSFULLY")
    print("="*60)

    return {
        "model": model,
        "features": features,
        "metrics": results
    }

results = novapay_pipeline(df)

from google.colab import files

files.download("novapay_fraud_model.pkl")
files.download("artifacts/lgb_model.pkl")
files.download("artifacts/scaler.pkl")
files.download("artifacts/encoders.pkl")
files.download("artifacts/features.pkl")
files.download("artifacts/shap_explainer.pkl")